server:
  port: 5555

spring:
  application:
    name: gateway
  cloud:
    discovery:
      enabled: true
    gateway:
      gdefault-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      metrics:
        enabled: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # http://localhost:5555/api/v1/auth/
        - id: ms-auth
          uri: lb://ms-auth
          predicates:
            - Path=/api/*/auth/**

          # http://localhost:5555/api/v1/products/{id}
        - id: ms-products
          uri: lb://ms-products
          predicates:
            - Path=/api/*/products/**

        - id: ms-orders
          uri: lb://ms-orders
          predicates:
            - Path=/api/*/orders/**,/api/*/cart/**
    loadbalancer:
      ribbon:
        enabled: false


eureka:
  client:
    fetch-registry: true
    service-url.defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
